version: "3.8"
services:
  postgres:
    image: postgres
    container_name: garbo_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  redis:
    image: redis
    container_name: garbo_redis
    ports:
      - "6379:6379"
  chroma:
    image: chromadb/chroma
    container_name: garbo_chroma
    ports:
      - "8000:8000"
  # ingestor:
  #   image: ghcr.io/nlmatics/nlm-ingestor
  #   container_name: garbo_ingestor
  #   ports:
  #     - "5001:5001"
  #docling: # Uncomment to for local Docling deployment
  #  image: quay.io/docling-project/docling-serve
  #  container_name: garbo_docling
  #  ports:
  #    - "5001:5001" # Mapped to a different host port to avoid conflict with NLM
  #  environment:
  #    - DOCLING_SERVE_ENABLE_UI=true
  #    - DOCLING_SERVE_MAX_SYNC_WAIT=3600
  #  healthcheck:
  #    test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
  #    interval: 30s
  #    timeout: 10s
  #   retries: 3
  #    start_period: 10s
