apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garbo

resources:
  - ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garbo-prod

resources:
  - ../../base
  - ingress.yaml
