apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garbo
spec:
  tls:
    - hosts:
        - api.klimatkollen.se
      secretName: api-klimatkollen-se-tls
  rules:
    - host: api.klimatkollen.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garbo-api
                port:
                  number: 80
